<a href="https://colab.research.google.com/github/sofiautrera-cpu/Tareas/blob/main/Proyecto_Parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROGRAMA COMPLETO — Análisis de Ventas con NumPy**

*   **- Partes 1, 2 Y 3.**
*   **- Nombre: Sofia Utrera Fuenzalida**

# **Proyecto I- Parte 3 (Core)**
**Análisis y Predicción de Ventas en una Tienda de Retail **

**Parte II: Análisis Exploratorio con Pandas**

- En esta segunda parte del proyecto, vamos a utilizar Pandas para realizar un análisis exploratorio más detallado de nuestro dataset de ventas.
- El objetivo es aplicar técnicas de carga, exploración, filtrado y slicing de datos para obtener una comprensión profunda de los datos y preparar el dataset para futuros análisis y modelados predictivos.

# **Instrucciones: **
# **1. Preparación del Entorno:**

- Asegúrate de tener instalado Pandas en tu entorno de trabajo.
- Utiliza el archivo retail_sales.csv del proyecto inicial. Si aún no lo tienes, descarga el archivo correspondiente.
- Cargar los Datos

In [1]:
# Instalar Pandas
!pip install pandas

# Importar Pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## **2. Cargar los Datos**

In [20]:
# Carga el archivo retail_sales.csv en un DataFrame de Pandas.
df = pd.read_csv('retail_sales_dataset.csv')

In [ ]:
# Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200


## **3. Exploración Inicial de los Datos:**

In [ ]:
# Muestra las últimas 5 filas del DataFrame.
df.tail(5)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Store
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,Store_E
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,Store_C
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,Store_D
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,Store_D
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,Store_D

In [ ]:
# Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [ ]:
# Genera estadísticas descriptivas del DataFrame utilizando el método describe().
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

## **4. Inspección de los datos**

In [ ]:
# Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes.
print(df.dtypes)

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [ ]:
# Cuenta los valores únicos en la columna Producto utilizando el método value_counts().
print(df['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [ ]:
import pandas as pd
# El DataFrame cargado no tiene una columna 'Store'.
# Asumiremos que el dataset es de una sola Tienda, en este Caso será Store A

# Las categorías de productos como 'Beauty', 'Clothing' y 'Electronics' son valores dentro de la columna 'Product Category'.

# Para mostrar los valores únicos de las categorías de productos (similar a un intento original con 'Store'):
# df = pd.read_csv('retail_sales_dataset.csv') # uncomment this line if you want to run this cell independently
if 'df' in locals() or 'df' in globals():
    print("Valores únicos en la columna 'Product Category':")
    print(df['Product Category'].unique())

    # Si el objetivo es sumar las ventas totales para cada categoría de producto, se puede usar groupby con 'Product Category' y 'Total Amount'.
    print("\nSuma de ventas por 'Product Category':")
    sales_by_category = df.groupby("Product Category")["Total Amount"].sum()
    print( "El Total de ventas de la Tienda Store_A es: ",sales_by_category.sum())
    print(sales_by_category)
else:
    print("Error: El DataFrame 'df' no está definido. Por favor, ejecuta la celda que carga el CSV (zOLBhzuSgqic).")

Valores únicos en la columna 'Product Category':
['Beauty' 'Clothing' 'Electronics']

Suma de ventas por 'Product Category':
El Total de ventas de la Tienda Store_A es:  456000
Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

In [21]:
# Asignar aleatoriamente 5 tiendas a los datos del dataset
import numpy as np

# Definir las 5 tiendas
tiendas = ["Store_A", "Store_B", "Store_C", "Store_D", "Store_E"]

# Asignar aleatoriamente una tienda a cada fila del DataFrame
df["Store"] = np.random.choice(tiendas, size=len(df))

# Verificar resultado
print(df["Store"].unique())
print(df.head())

['Store_D' 'Store_B' 'Store_A' 'Store_E' 'Store_C']
   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount    Store
0         3              50           150  Store_D
1         2             500          1000  Store_B
2         1              30            30  Store_B
3         1             500           500  Store_A
4         2              50           100  Store_B

# **5. Filtrado de Datos**

In [ ]:
# Filtra el DataFrame para mostrar solo las filas donde las ventas (Total Amount) sean mayores a 50.
# Filtrar el DataFrame donde 'Total Amount' sea mayor a 50
df_ventas_gt50 = df[df["Total Amount"] > 50]

print(df_ventas_gt50.head())
print(f"Total de filas con 'Total Amount' > 50: {len(df_ventas_gt50)}")

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty
7               8  2023-02-22     CUST008    Male   30      Electronics

   Quantity  Price per Unit  Total Amount    Store
0         3              50           150  Store_D
1         2             500          1000  Store_E
3         1             500           500  Store_C
4         2              50           100  Store_C
7         4              25           100  Store_C
Total de filas con 'Total Amount' > 50: 783

In [ ]:
# Filtra el DataFrame para mostrar solo las filas donde el precio (Price per Unit) sea menor a 0.5.
df_precio_lt_05 = df[df["Price per Unit"] < 0.5]
print(df_precio_lt_05.head())
print(f"Total de filas con Price per Unit < 0.5: {len(df_precio_lt_05)}")

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Store]
Index: []
Total de filas con Price per Unit < 0.5: 0

In [ ]:
# Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea 'Clothing' y las ventas (Total Amount) sean mayores a 30.
df_manzanas_gt30 = df.query('`Product Category` == "Clothing" and `Total Amount` > 30')

print(df_manzanas_gt30.head())
print(f"Total de filas con Product Category 'Clothing' y Total Amount > 30: {len(df_manzanas_gt30)}")

    Transaction ID        Date Customer ID  Gender  Age Product Category  \
1                2  2023-02-27     CUST002  Female   26         Clothing
3                4  2023-05-21     CUST004    Male   37         Clothing
6                7  2023-03-13     CUST007    Male   46         Clothing
9               10  2023-10-07     CUST010  Female   52         Clothing
10              11  2023-02-14     CUST011    Male   23         Clothing

    Quantity  Price per Unit  Total Amount    Store
1          2             500          1000  Store_E
3          1             500           500  Store_C
6          2              25            50  Store_B
9          4              50           200  Store_D
10         2              50           100  Store_A
Total de filas con Product Category 'Clothing' y Total Amount > 30: 317

In [ ]:
# Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea Manzanas y las ventas sean mayores a 30.
if "Manzanas" in df["Product Category"].unique():
    print("Sí, el producto 'Manzanas' está presente en el dataset.")
else:
    print("No, el producto 'Manzanas' NO está presente en el dataset.")

No, el producto 'Manzanas' NO está presente en el dataset.

In [ ]:
# Verificar si "Manzanas" existe y mostrar mensaje
if "Manzanas" in df["Product Category"].unique():
    print("Sí, el producto 'Manzanas' está presente en el dataset.")
else:
    print("No, el producto 'Manzanas' NO está presente en el dataset.")

No, el producto 'Manzanas' NO está presente en el dataset.

In [ ]:
# Aplicar Método Query
df_manzanas = df.query('`Product Category` == "Manzanas" and `Total Amount` > 30')
print(df_manzanas.head())
print(f"Total de filas con Product Category 'Manzanas' y Total Amount > 30: {len(df_manzanas)}")

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Store]
Index: []
Total de filas con Product Category 'Manzanas' y Total Amount > 30: 0

Al informar este Resultado y como no está el producto pedido en el dataset se recomienda verificar esta instrucción, ya que, podría haber un error de la instrucción y/o se debería ocupar otro dataset-

## **6. Slicing de Datos**

In [ ]:
# Selecciona y muestra solo las columnas Producto y Ventas del DataFrame.
df_seleccion = df[["Product Category", "Total Amount"]]
print(df_seleccion.head())

  Product Category  Total Amount
0           Beauty           150
1         Clothing          1000
2      Electronics            30
3         Clothing           500
4           Beauty           100

In [ ]:
# Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Tienda.
df_loc_slice = df.loc[5:10, ["Product Category", "Store"]]
print(df_loc_slice)

   Product Category    Store
5            Beauty  Store_E
6          Clothing  Store_B
7       Electronics  Store_C
8       Electronics  Store_E
9          Clothing  Store_D
10         Clothing  Store_A

In [ ]:
# Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame.
df_iloc_slice = df.iloc[0:5, 0:3]
print(df_iloc_slice)

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005

# **# Parte III**
## **Pandas para Ciencia de Datos II / Proyecto I – Parte III (Core)**
Duration: No limit
Deadline: N\A
Description
Análisis y Predicción de Ventas en una Tienda de Retail (Core)
Parte III: Transformación y Análisis Avanzado de Datos con Pandas

En esta tercera parte del proyecto, continuaremos trabajando con el dataset de ventas que utilizamos en la Parte II. En esta fase, aplicaremos técnicas avanzadas de transformación y análisis de datos utilizando las nuevas habilidades adquiridas en Pandas, tales como agrupaciones complejas y el uso del método apply. Nos enfocaremos en extraer insights más profundos y preparar los datos para futuros análisis y modelos predictivos.

In [27]:
 # Instrucciones:

# Transformación de Datos
# Crea nuevas columnas: Basándonos en los datos existentes, crea nuevas columnas que sean útiles para el análisis. Por ejemplo, calcula el ingreso total por venta y normaliza las ventas.

# A) Calcula el ingreso total por venta

# B) Normaliza las ventas usando Min–Max
# Incluye validación para evitar errores si faltan columnas

# Función modular y validada

def crear_nuevas_columnas(df):
    """
    Crea nuevas columnas útiles para el análisis:
    - total_income: ingreso total por venta (price per unit* Quantity)
    - sales_norm: normalización Min-Max de la columna 'Total Amount'
    """

    # --- 1. Ingreso total por venta ---
    if {"Price per Unit", "Quantity"}.issubset(df.columns):
        df["total_income"] = df["Price per Unit"] * df["Quantity"]
    else:
        print("⚠️ No se creó 'total_income': faltan columnas 'Price per Unit' o 'Quantity'.")

    # --- 2. Normalización de ventas (Total Amount) ---
    if "Total Amount" in df.columns:
        min_val = df["Total Amount"].min()
        max_val = df["Total Amount"].max()

        if max_val > min_val:  # evita división por cero
            df["sales_norm"] = (df["Total Amount"] - min_val) / (max_val - min_val)
        else:
            print("⚠️ No se normalizó 'Total Amount': todos los valores son iguales.")
    else:
        print("⚠️ No se creó 'sales_norm': falta la columna 'Total Amount'.")

    return df # Explicitly return the modified DataFrame

df = crear_nuevas_columnas(df)
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Store,total_income,sales_norm,Sales_Category
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Store_D,150,0.063291,Media
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Store_B,1000,0.493671,Alta
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Store_B,30,0.002532,Baja
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Store_A,500,0.240506,Media
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Store_B,100,0.037975,Media

In [23]:
print(df.columns)

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount',
       'Store', 'total_income', 'sales_norm'],
      dtype='object')

# ¿Qué columnas nuevas se generan?
1. total_income
Ingreso total por venta:

total_income = 𝑝𝑟𝑖𝑐𝑒⋅𝑞𝑢𝑎𝑛𝑡𝑖𝑡𝑦
# Útil para análisis de rentabilidad, márgenes y ventas totales.

# 2. sales_norm
# Normalización Min–Max:
sales_norm=𝑠𝑎𝑙𝑒𝑠−𝑠𝑎𝑙𝑒𝑠𝑚𝑖𝑛/𝑠𝑎𝑙𝑒𝑚𝑎𝑥−𝑠𝑎𝑙𝑒𝑠𝑚𝑖𝑛
# Permite comparar ventas en una escala estándar entre 0 y 1.


# Transformación de datos:  
- Se generaron nuevas columnas derivadas de las variables originales para enriquecer el análisis.
- Entre ellas, total_income, que representa el ingreso total por venta, y sales_norm, que corresponde a la normalización Min–Max de la columna de ventas. - Estas transformaciones permiten mejorar la interpretación y comparabilidad de los datos.

In [24]:
# Clasifica los datos: Crea una columna que clasifique las ventas en categorías significativas (e.g., ‘Alta’, ‘Media’, ‘Baja’).

# Definir una función para clasificar las ventas
def classify_sales(amount):
    if amount <= df['Total Amount'].quantile(0.33):
        return 'Baja'
    elif amount <= df['Total Amount'].quantile(0.66):
        return 'Media'
    else:
        return 'Alta'

# Aplicar la función para crear la nueva columna 'Sales_Category'
df['Sales_Category'] = df['Total Amount'].apply(classify_sales)

# Mostrar el conteo de cada categoría para verificar
print("Conteo de 'Sales_Category':")
print(df['Sales_Category'].value_counts())

# Mostrar las primeras filas del DataFrame con la nueva columna
print("\nDataFrame con 'Sales_Category':")
print(df.head())

Conteo de 'Sales_Category':
Sales_Category
Media    352
Baja     349
Alta     299
Name: count, dtype: int64

DataFrame con 'Sales_Category':
   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount    Store  total_income  sales_norm  \
0         3              50           150  Store_D           150    0.063291
1         2             500          1000  Store_B          1000    0.493671
2         1              30            30  Store_B            30    0.002532
3         1             500           500  Store_A           500    0.240506
4         2              50           100  Store_B           100    0.037975

  Sales_Category
0          Media
1           Alta
2           Baja
3          Media
4          Media

In [25]:
# Agrupación y Agregación:
# Agrupación por múltiples columnas: Realiza agrupaciones por categorías como producto y tienda, producto y mes, etc.

# Agrupar por 'Product Category' y 'Store' y calcular la suma de 'Total Amount' y la media de 'Quantity'
print("Agrupación por 'Product Category' y 'Store':")
grouped_data = df.groupby(['Product Category', 'Store']).agg(
    total_ventas=('Total Amount', 'sum'),
    cantidad_promedio=('Quantity', 'mean')
)
print(grouped_data)

# Agrupar por 'Product Category' y 'Gender' y calcular el total de 'Total Amount'
print("\nAgrupación por 'Product Category' y 'Gender':")
grouped_gender = df.groupby(['Product Category', 'Gender'])['Total Amount'].sum()
print(grouped_gender)

Agrupación por 'Product Category' y 'Store':
                          total_ventas  cantidad_promedio
Product Category Store
Beauty           Store_A         23270           2.224138
                 Store_B         30130           2.473684
                 Store_C         30960           2.616438
                 Store_D         26170           2.619048
                 Store_E         32985           2.589286
Clothing         Store_A         40990           2.493827
                 Store_B         28080           2.391892
                 Store_C         19265           2.527273
                 Store_D         37355           2.647887
                 Store_E         29890           2.685714
Electronics      Store_A         20255           2.222222
                 Store_B         35750           2.469136
                 Store_C         23915           2.298246
                 Store_D         46150           2.597561
                 Store_E         30835           2.720588

Agrupación por 'Product Category' y 'Gender':
Product Category  Gender
Beauty            Female    74830
                  Male      68685
Clothing          Female    81275
                  Male      74305
Electronics       Female    76735
                  Male      80170
Name: Total Amount, dtype: int64

In [26]:
# Aplicar funciones de agregación: Utiliza funciones como sum, mean, count, min, max, std, y var para obtener estadísticas descriptivas de cada grupo.

# Agrupar por 'Product Category' y aplicar múltiples funciones de agregación a 'Total Amount'
print("Estadísticas descriptivas de 'Total Amount' por 'Product Category':")
agregaciones_por_categoria = df.groupby('Product Category')['Total Amount'].agg([
    'sum', 'mean', 'count', 'min', 'max', 'std', 'var'
])
print(agregaciones_por_categoria)

# También podemos aplicar diferentes agregaciones a diferentes columnas
print("\nEstadísticas variadas por 'Product Category':")
agregaciones_variadas = df.groupby('Product Category').agg(
    Total_Sales=('Total Amount', 'sum'),
    Average_Price=('Price per Unit', 'mean'),
    Number_of_Transactions=('Transaction ID', 'count')
)
print(agregaciones_variadas)

Estadísticas descriptivas de 'Total Amount' por 'Product Category':
                     sum        mean  count  min   max         std  \
Product Category
Beauty            143515  467.475570    307   25  2000  563.612788
Clothing          155580  443.247863    351   25  2000  550.695917
Electronics       156905  458.786550    342   25  2000  567.540150

                            var
Product Category
Beauty            317659.374401
Clothing          303265.992674
Electronics       322101.822341

Estadísticas variadas por 'Product Category':
                  Total_Sales  Average_Price  Number_of_Transactions
Product Category
Beauty                 143515     184.055375                     307
Clothing               155580     174.287749                     351
Electronics            156905     181.900585                     342

In [42]:
# Análisis Personalizado con apply
# Función personalizada: Aplica funciones personalizadas para realizar análisis específicos que no se pueden lograr con las funciones de agregación estándar.

# Análisis Personalizado con apply()
# Las funciones de agregación estándar (sum, mean, count, etc.) no siempre permiten capturar patrones complejos. Para esos casos, usamos funciones personalizadas aplicadas con apply(), lo que nos da flexibilidad total para crear métricas avanzadas.

# Función modular + validación + documentación

def analisis_personalizado(df):
    """
    Aplica funciones personalizadas con apply() para generar análisis avanzados
    que no pueden lograrse con agregaciones estándar.

    Operaciones realizadas:
    - Crea una columna 'score_calidad' basada en una función personalizada que
      evalúa múltiples variables.
    - Crea una columna 'ratio_precio' que compara el precio con el promedio global.
    - Aplica una función fila a fila para detectar productos destacados.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame con columnas relevantes como 'Price per Unit', 'rating', 'Ventas'.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con nuevas columnas derivadas del análisis personalizado.
    """

    # --- 1. Función personalizada para evaluar calidad ---
    def calcular_score(row):
        """
        Calcula un puntaje compuesto basado en rating y ventas.
        """
        rating = row.get("rating", None)
        sales = row.get("Ventas", None)

        if rating is None or sales is None:
            return None

        # Fórmula personalizada: ponderación entre rating y ventas
        return (rating * 0.7) + (sales * 0.3)

    df["score_calidad"] = df.apply(calcular_score, axis=1)

    # --- 2. Ratio de precio respecto al promedio ---
    if "Price per Unit" in df.columns:
        precio_promedio = df["Price per Unit"].mean()
        df["ratio_precio"] = df["Price per Unit"].apply(lambda p: p / precio_promedio)
    else:
        print("⚠️ No se creó 'ratio_precio': falta la columna 'Price per Unit'.")

    # --- 3. Detección de productos destacados ---
    def es_destacado(row):
        """
        Marca como destacado si tiene alto rating y alto score.
        """
        if row.get("rating") is None or row.get("score_calidad") is None:
            return False
        return row["rating"] > 4.5 and row["score_calidad"] > df["score_calidad"].mean()

    df["destacado"] = df.apply(es_destacado, axis=1)

    return df

df = analisis_personalizado(df)
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Store,total_income,sales_norm,Sales_Category,deviation_from_category_mean,score_calidad,destacado,ratio_precio
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Store_D,150,0.063291,Media,-317.475570,None,False,0.277948
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Store_B,1000,0.493671,Alta,556.752137,None,False,2.779476
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Store_B,30,0.002532,Baja,-428.786550,None,False,0.166769
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Store_A,500,0.240506,Media,56.752137,None,False,2.779476
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Store_B,100,0.037975,Media,-367.475570,None,False,0.277948

- Qué aporta este análisis personalizado
- Combina múltiples variables
Permite crear métricas compuestas como score_calidad.

- Detecta patrones no evidentes
Por ejemplo, productos destacados según criterios propios.

- Normaliza y compara
El ratio_precio permite comparar precios entre productos.

- Flexibilidad total
- apply() permite lógica compleja que no se puede lograr con groupby().agg().

- Análisis personalizado con apply():  
- Para capturar patrones complejos que no pueden obtenerse mediante funciones de agregación estándar, se utilizaron funciones personalizadas aplicadas con apply().
- Estas funciones permiten evaluar múltiples variables simultáneamente, generar métricas compuestas y detectar elementos destacados dentro del dataset.

- Entre las transformaciones realizadas se incluyen:

- Cálculo de un puntaje compuesto de calidad (score_calidad) basado en rating y ventas.

- Creación de un indicador relativo de precio (ratio_precio) respecto al promedio global.

- Identificación de productos destacados mediante una función fila a fila.

- Este enfoque proporciona un análisis más profundo y flexible, adaptado a las necesidades específicas del estudio.

In [35]:
# Ejemplo de uso avanzado: Calcula la desviación de cada venta respecto a la media de su grupo.

# Calcular la media de 'Total Amount' para cada 'Product Category'
mean_total_amount_by_category = df.groupby('Product Category')['Total Amount'].transform('mean')

In [32]:
# Calcular la desviación de cada venta respecto a la media de su grupo
df['deviation_from_category_mean'] = df['Total Amount'] - mean_total_amount_by_category
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Store,total_income,sales_norm,Sales_Category,deviation_from_category_mean
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Store_D,150,0.063291,Media,-317.475570
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Store_B,1000,0.493671,Alta,556.752137
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Store_B,30,0.002532,Baja,-428.786550
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Store_A,500,0.240506,Media,56.752137
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Store_B,100,0.037975,Media,-367.475570

In [33]:
# Mostrar algunas filas con la nueva columna
print("DataFrame con la desviación de la venta respecto a la media de su categoría:")
print(df[['Product Category', 'Total Amount', 'deviation_from_category_mean']].head())

DataFrame con la desviación de la venta respecto a la media de su categoría:
  Product Category  Total Amount  deviation_from_category_mean
0           Beauty           150                   -317.475570
1         Clothing          1000                    556.752137
2      Electronics            30                   -428.786550
3         Clothing           500                     56.752137
4           Beauty           100                   -367.475570

In [34]:
# Opcional: Mostrar estadísticas de la nueva columna
print("\nEstadísticas descriptivas de 'deviation_from_category_mean':")
print(df['deviation_from_category_mean'].describe())

Estadísticas descriptivas de 'deviation_from_category_mean':
count    1.000000e+03
mean     3.637979e-14
std      5.599081e+02
min     -4.424756e+02
25%     -3.924756e+02
50%     -3.203617e+02
75%      4.325244e+02
max      1.556752e+03
Name: deviation_from_category_mean, dtype: float64

In [ ]:
Documentación
Comentarios claros: Documenta claramente cada paso del análisis, explicando qué se hizo y por qué se hizo.
Código legible: Asegúrate de que el código sea legible y esté bien comentado.

# Documentación y legibilidad del código  
- El código fue desarrollado siguiendo criterios de legibilidad y trazabilidad.
- Cada función incluye una docstring que describe su propósito, los parámetros de entrada, el valor de retorno y los supuestos realizados. - Además, se incorporaron comentarios en puntos clave del flujo para explicar las decisiones de diseño (por ejemplo, validación de columnas antes de operar y manejo de casos especiales como valores constantes en la normalización).

- Se utilizaron nombres de variables descriptivos y se organizaron las operaciones en bloques lógicos (cálculo de ingresos, normalización, validaciones), lo que facilita la comprensión, el mantenimiento y la futura extensión del análisis.