<a href="https://colab.research.google.com/github/sofiautrera-cpu/Tareas/blob/main/Proyecto_Parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROGRAMA COMPLETO — Análisis de Ventas con NumPy**

*   **- Partes 1 y 2.**
*   **- Nombre: Sofia Utrera Fuenzalida**

# **Proyecto I- Parte 2 (Core)**
**Análisis y Predicción de Ventas en una Tienda de Retail **

**Parte II: Análisis Exploratorio con Pandas**

- En esta segunda parte del proyecto, vamos a utilizar Pandas para realizar un análisis exploratorio más detallado de nuestro dataset de ventas.
- El objetivo es aplicar técnicas de carga, exploración, filtrado y slicing de datos para obtener una comprensión profunda de los datos y preparar el dataset para futuros análisis y modelados predictivos.

# **Instrucciones: **
# **1. Preparación del Entorno:**

- Asegúrate de tener instalado Pandas en tu entorno de trabajo.
- Utiliza el archivo retail_sales.csv del proyecto inicial. Si aún no lo tienes, descarga el archivo correspondiente.
- Cargar los Datos

In [3]:
# Instalar Pandas
!pip install pandas

# Importar Pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## **2. Cargar los Datos**

In [4]:
# Carga el archivo retail_sales.csv en un DataFrame de Pandas.
df = pd.read_csv('retail_sales_dataset.csv')

In [5]:
# Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200


## **3. Exploración Inicial de los Datos:**

In [26]:
# Muestra las últimas 5 filas del DataFrame.
df.tail(5)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Store
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,Store_E
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,Store_C
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,Store_D
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,Store_D
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,Store_D

In [7]:
# Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [8]:
# Genera estadísticas descriptivas del DataFrame utilizando el método describe().
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

## **4. Inspección de los datos**

In [9]:
# Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes.
print(df.dtypes)

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [10]:
# Cuenta los valores únicos en la columna Producto utilizando el método value_counts().
print(df['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [24]:
import pandas as pd
# El DataFrame cargado no tiene una columna 'Store'.
# Asumiremos que el dataset es de una sola Tienda, en este Caso será Store A

# Las categorías de productos como 'Beauty', 'Clothing' y 'Electronics' son valores dentro de la columna 'Product Category'.

# Para mostrar los valores únicos de las categorías de productos (similar a un intento original con 'Store'):
# df = pd.read_csv('retail_sales_dataset.csv') # uncomment this line if you want to run this cell independently
if 'df' in locals() or 'df' in globals():
    print("Valores únicos en la columna 'Product Category':")
    print(df['Product Category'].unique())

    # Si el objetivo es sumar las ventas totales para cada categoría de producto, se puede usar groupby con 'Product Category' y 'Total Amount'.
    print("\nSuma de ventas por 'Product Category':")
    sales_by_category = df.groupby("Product Category")["Total Amount"].sum()
    print( "El Total de ventas de la Tienda Store_A es: ",sales_by_category.sum())
    print(sales_by_category)
else:
    print("Error: El DataFrame 'df' no está definido. Por favor, ejecuta la celda que carga el CSV (zOLBhzuSgqic).")

Valores únicos en la columna 'Product Category':
['Beauty' 'Clothing' 'Electronics']

Suma de ventas por 'Product Category':
El Total de ventas de la Tienda Store_A es:  456000
Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

In [25]:
# Asignar aleatoriamente 5 tiendas a los datos del dataset
import numpy as np

# Definir las 5 tiendas
tiendas = ["Store_A", "Store_B", "Store_C", "Store_D", "Store_E"]

# Asignar aleatoriamente una tienda a cada fila del DataFrame
df["Store"] = np.random.choice(tiendas, size=len(df))

# Verificar resultado
print(df["Store"].unique())
print(df.head())

['Store_D' 'Store_E' 'Store_C' 'Store_B' 'Store_A']
   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount    Store
0         3              50           150  Store_D
1         2             500          1000  Store_E
2         1              30            30  Store_D
3         1             500           500  Store_C
4         2              50           100  Store_C

# **5. Filtrado de Datos**

In [31]:
# Filtra el DataFrame para mostrar solo las filas donde las ventas (Total Amount) sean mayores a 50.
# Filtrar el DataFrame donde 'Total Amount' sea mayor a 50
df_ventas_gt50 = df[df["Total Amount"] > 50]

print(df_ventas_gt50.head())
print(f"Total de filas con 'Total Amount' > 50: {len(df_ventas_gt50)}")

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty
7               8  2023-02-22     CUST008    Male   30      Electronics

   Quantity  Price per Unit  Total Amount    Store
0         3              50           150  Store_D
1         2             500          1000  Store_E
3         1             500           500  Store_C
4         2              50           100  Store_C
7         4              25           100  Store_C
Total de filas con 'Total Amount' > 50: 783

In [35]:
# Filtra el DataFrame para mostrar solo las filas donde el precio (Price per Unit) sea menor a 0.5.
df_precio_lt_05 = df[df["Price per Unit"] < 0.5]
print(df_precio_lt_05.head())
print(f"Total de filas con Price per Unit < 0.5: {len(df_precio_lt_05)}")

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Store]
Index: []
Total de filas con Price per Unit < 0.5: 0

In [38]:
# Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea 'Clothing' y las ventas (Total Amount) sean mayores a 30.
df_manzanas_gt30 = df.query('`Product Category` == "Clothing" and `Total Amount` > 30')

print(df_manzanas_gt30.head())
print(f"Total de filas con Product Category 'Clothing' y Total Amount > 30: {len(df_manzanas_gt30)}")

    Transaction ID        Date Customer ID  Gender  Age Product Category  \
1                2  2023-02-27     CUST002  Female   26         Clothing
3                4  2023-05-21     CUST004    Male   37         Clothing
6                7  2023-03-13     CUST007    Male   46         Clothing
9               10  2023-10-07     CUST010  Female   52         Clothing
10              11  2023-02-14     CUST011    Male   23         Clothing

    Quantity  Price per Unit  Total Amount    Store
1          2             500          1000  Store_E
3          1             500           500  Store_C
6          2              25            50  Store_B
9          4              50           200  Store_D
10         2              50           100  Store_A
Total de filas con Product Category 'Clothing' y Total Amount > 30: 317

In [41]:
# Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea Manzanas y las ventas sean mayores a 30.
if "Manzanas" in df["Product Category"].unique():
    print("Sí, el producto 'Manzanas' está presente en el dataset.")
else:
    print("No, el producto 'Manzanas' NO está presente en el dataset.")

No, el producto 'Manzanas' NO está presente en el dataset.

In [42]:
# Verificar si "Manzanas" existe y mostrar mensaje
if "Manzanas" in df["Product Category"].unique():
    print("Sí, el producto 'Manzanas' está presente en el dataset.")
else:
    print("No, el producto 'Manzanas' NO está presente en el dataset.")

No, el producto 'Manzanas' NO está presente en el dataset.

In [48]:
# Aplicar Método Query
df_manzanas = df.query('`Product Category` == "Manzanas" and `Total Amount` > 30')
print(df_manzanas.head())
print(f"Total de filas con Product Category 'Manzanas' y Total Amount > 30: {len(df_manzanas)}")

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Store]
Index: []
Total de filas con Product Category 'Manzanas' y Total Amount > 30: 0

Al informar este Resultado y como no está el producto pedido en el dataset se recomienda verificar esta instrucción, ya que, podría haber un error de la instrucción y/o se debería ocupar otro dataset-

## **6. Slicing de Datos**

In [51]:
# Selecciona y muestra solo las columnas Producto y Ventas del DataFrame.
df_seleccion = df[["Product Category", "Total Amount"]]
print(df_seleccion.head())

  Product Category  Total Amount
0           Beauty           150
1         Clothing          1000
2      Electronics            30
3         Clothing           500
4           Beauty           100

In [54]:
# Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Tienda.
df_loc_slice = df.loc[5:10, ["Product Category", "Store"]]
print(df_loc_slice)

   Product Category    Store
5            Beauty  Store_E
6          Clothing  Store_B
7       Electronics  Store_C
8       Electronics  Store_E
9          Clothing  Store_D
10         Clothing  Store_A

In [55]:
# Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame.
df_iloc_slice = df.iloc[0:5, 0:3]
print(df_iloc_slice)

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005